# Generated by Django 4.0.5 on 2025-04-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiledataplan',
            name='_type',
            field=models.CharField(default='SME', max_length=100),
            preserve_default=False,
        ),
    ]
