# Generated by Django 4.2.23 on 2025-07-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_exams_cabletvplan_vt_pass_variation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiledataplan',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
