# Generated by Django 4.0.5 on 2022-06-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='is_successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactions',
            name='transaction_no',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
