# Generated by Django 4.0.5 on 2022-07-30 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transactions_transaction_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='transaction_no',
        ),
    ]
