# Generated by Django 4.0.5 on 2022-10-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_transactions_transaction_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='phone_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
