# Generated by Django 4.0.5 on 2022-10-20 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transactions_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='phone_no',
            new_name='number',
        ),
    ]
