# Generated by Django 4.0.5 on 2025-02-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_rename_phone_no_transactions_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
