# Generated by Django 4.0.5 on 2025-03-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transactions_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
