# Generated by Django 4.0.5 on 2022-07-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='wallet',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
