# Generated by Django 4.0.5 on 2025-02-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_useraccount_wallet_delete_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='default',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
