# Generated by Django 4.0.5 on 2025-02-08 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_useraccount_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='default',
            new_name='verified',
        ),
    ]
