# Generated by Django 4.0.5 on 2025-03-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_default_useraccount_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='personal_account_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
