# Generated by Django 4.0.5 on 2025-03-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_useraccount_personal_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='personal_account_number',
        ),
    ]
