# Generated by Django 4.0.5 on 2025-04-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_useraccount_personal_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='wallet',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
