# Generated by Django 4.0.5 on 2025-05-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_useraccount_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='transaction_pin',
            field=models.PositiveIntegerField(blank=True, max_length=4, null=True),
        ),
    ]
