# Generated by Django 4.0.5 on 2025-05-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_useraccount_transaction_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='transaction_pin',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
