# Generated by Django 4.0.5 on 2025-05-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardholder',
            name='identity_verification_status',
            field=models.CharField(default='PENDING', max_length=250),
        ),
    ]
