# Generated by Django 4.0.5 on 2025-06-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cardholder_identity_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardholder',
            name='card_holder_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
