# Generated by Django 4.0.5 on 2025-06-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_cardholder_card_holder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardholder',
            name='id_image',
            field=models.ImageField(default='hello.jpg', upload_to='media/id'),
            preserve_default=False,
        ),
    ]
