# Generated by Django 4.0.5 on 2025-06-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_cardholder_id_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(default='VIRTUAL', max_length=250),
        ),
        migrations.AddField(
            model_name='card',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cardholder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cardholder',
            name='livemode',
            field=models.BooleanField(default=False),
        ),
    ]
