# Generated by Django 4.0.5 on 2025-06-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_card_type_card_is_active_cardholder_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_currency',
            field=models.CharField(default='USD', max_length=250),
        ),
    ]
