# Generated by Django 4.0.5 on 2025-07-12 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_card_card_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_name',
        ),
    ]
