# Generated by Django 4.0.5 on 2025-07-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_remove_card_card_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_expiry',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='card_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='last_four',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
