# Generated by Django 4.0.5 on 2025-07-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_card_card_expiry_card_card_name_card_last_four'),
    ]

    operations = [
        migrations.CreateModel(
            name='DollarToNaira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
