# Generated by Django 4.0.5 on 2025-07-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_dollartonaira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollartonaira',
            name='rate',
            field=models.FloatField(),
        ),
    ]
